auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Pinder's Page
url: http://pinderpeng.org
feed: /atom.xml
author_info: <a href="http://pinderpeng.org/">Pinder</a>
